<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="Vortex_Equipment.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Calibri Light&quot;; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Vortex Equipment has been serving the fitness equipment needs of everyday New Zealanders for over 20 years. From its humble beginnings, located on the corner of Moorhouse &amp; Montreal Street in Christchurch,  Vortex Equipment Fitness was established in 1993 by Managing Director &amp; Business Owner – Gary Bourke. Since this time, Vortex Equipment Fitness has now grown to 12 retail store outlets nationwide including 6 super stores. To compliment our retail stores we operate an online store, employee 4 Regional Commercial Representatives, a Specialised Service/Parts Department, In-house call centre and dedicated online customer service team to answer your enquiries over the Internet.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Calibri Light&quot;; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        The Team at Vortex Equipment Fitness is committed to co-operating with the world’s leading fitness brands and equipment manufacturers to produce fitness equipment that is safe, effective and biomechanically superior, meeting the heavy demands of active New Zealanders.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Calibri Light&quot;; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        The  Vortex Equipment Fitness brand covers all fitness categories and we have, with our New Zealand owners and senior management, over 100 years’ combined experience in the New Zealand home fitness market. The passion to make New Zealand a fitter and healthier nation drives us to provide innovative and cutting edge technology from the world’s No. 1 fitness manufacturers and recognised brands such as Proform, NordicTrack, Healthrider, Golds Gym, Schwinn, Octane, Marcy, Inspire Fitness, BodySolid, Weider, Nautilus and more.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Calibri Light&quot;; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Our dedicated team have experience and/or qualifications in the fitness industry. We understand that everyone has individual goals and requirements, that&#39;s why our fitness professionals will help you decide on the correct product, educate you on how to use the equipment correctly and offer tips and advice on how to get optimal results from your training routine.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Calibri Light&quot;; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Talk to us today!</p>
</asp:Content>
